---
# Form running gradle locally

server:
    context-path: /api

security:
    ignored: /**

cors:
    allowed-origins: "*"
    allowed-methods: GET, PUT, POST, DELETE, PATCH
    allowed-headers: origin, content-type, accept, authorization
    exposed-headers:
    allow-credentials: true
    max-age: 1800

