
server:
    context-path: /api-stack
    session:
        cookie:
            http-only: true

management:
    security:
        enabled: false
    health:
      db:
        enabled: false

security:
    ignored: /**
