server:
    port: 8082

info:
    env: LOCAL

logging:
    config: config/logback-local.xml

spring:
    jpa:
        database: H2
        show-sql: true
    h2:
        console:
            enabled: true